pipeline {
  agent any
  triggers {
    githubPush()
  }
  stages {
    stage('install dependencies') {
      steps {
        script {
          dir('frontend/') {
            sh './prod_dependencies_frontend.sh'
          }
        }
      }
    }
    stage('deploy') {
      steps {
        script {
          dir('frontend/') {
            sh './deploy_frontend.sh'
          }
        }
      }
    }
  }
}
