version: "3"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database

  react:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "3000:3000"

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_INITDB_ARGS: "--username=admin"
