version: "3.9"

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=contest-platform-database

    volumes:
      - ./data/db:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

    volumes:
      - ./frontend:/app/frontend

    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=admin

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app/backend

    depends_on:
      - db
